def fail(message):
    print ('\nFAILED:  %s' % message)
    sys.exit(1)
