def assert_failure(self):
    assert (self.exception or self.return_code)
